### ISSUE TITLE
Could not load uc_build_tasks_r.dll

### ISSUE THREAD

**Issue by mediabuff** [UniqueCreator/UCEngine#1]
UCEngine-master\build\msbuild\ucdev_render.targets(85,5): error MSB4062: The "UniqueCreator.Build.Tasks.HLSLCompiler" task could not be loaded from the assembly C:\MyDevProjects\MyProjectsThirdPartyLibs\UCEngine-master\build\msbuild\..\..\src\tools\bin\x86\release\uc_build_tasks_r.dll. Could not load file or assembly 'file:///C:\MyDevProjects\MyProjectsThirdPartyLibs\UCEngine-master\src\tools\bin\x86\release\uc_build_tasks_r.dll' or one of its dependencies. The module was expected to contain an assembly manifest. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by UCChristianJones** [comment]
My apologizes. I only recently saw your raised issue. 
This should however now be resolved.

We have used git lfs to commit larger files to git (https://git-lfs.github.com/), so if you do not have this installed you will need to do so.

Also if you downloaded the code as a zip file, this will not have any of the larger files, this is due to git lfs again. You will need to do a clone (with git lfs installed on your computer) in order to successfully pull back all required files.

I hope this helps.

If not, please let me know.
